# Your Name or Company
title: Lions Den CNX

# Description of your website. This is used for social sharing.
description:  Profile of a private health and wellbeing club. 

# A brief blurb about yourself
content: Move heavy thing make sad head noises quieter 

# Add your social links
social:
  - platform: instagram
    url: https://instagram.com/lionsdencnx
  - platform: facebook
    url: https://facebook.com/lionsdencnx

# General settings
url: http://lionsdencnx.com
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
#google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
