# Your Name or Company
title: Lions Den CNX

# Description of your website. This is used for social sharing.
description:  Profile of a private health and wellbeing club. 

# A brief blurb about yourself
content: Train with us in Chiang Mai, Thailand.

# Add your social links
social:
  - platform: line official
    url: https://lin.ee/E7P1Tfz
  - platform: instagram
    url: https://instagram.com/lionsdencnx
  - platform: map
    url: https://maps.app.goo.gl/qEYyWWvP2nVe9auX7

# General settings
url: http://lionsdencnx.com
# baseurl: "/uni" 
markdown: kramdown
sharing_image: half-sm.jpg
google_analytics: "G-XDZJ0XV2JH" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
