# Your Name or Company
title: Uni Kravitz

# A brief blurb about yourself
content: Nullam id dolor id nibh ultricies vehicula ut id elit. Cras mattis consectetur purus sit amet fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum.

url: http://brianmaierjr.github.com/uni
markdown: kramdown

# Half layout options
half_side: right
half_image: woman-half.jpg

# Full layout options
full_image: man-full.jpg
full_text_color: light # dark or light
full_text_position: right # left, right or center

# Card layout options
card_image: card.jpg

# Add your social links
social:
  - platform: github
    url: https://github.com/brianmaierjr
  - platform: facebook
    url: https://facebook.com/brianmaierjr
  - platform: twitter
    url: https://twitter.com/brianmaierjr
  - platform: linkedin
    url: brianmaierjr


# Google Analytics for tracking
google_analytics: "UA-58263416-1"
